/* eslint-disable @next/next/no-page-custom-font */
import InvitationPageTemplate from "@/templates/InvitationPage/InvitationPageTemplate";
import { NextPage } from "next";
import Head from "next/head";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>invitation-test-iqbal</title>
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Raleway&display=swap" rel="stylesheet" />
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <InvitationPageTemplate />
    </>
  );
};

export default Index;
